name: cmp
analytics: {}
github: true
description: A developer
author: {}
color:
  lightness: 0.7632346
  brandColors:
    - '#020001'
    - '#FDFDFD'
    - '#613312'
    - '#73746F'
    - '#CAA06E'
  saturation: 0.2470101
  brandStrength: 1
  rhythmicContrast: 0.8495885
content: []
layout_spectrum: 0.4097744
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content_rating:
  adult: false
typography_spectrum: 0.349624
opengraph: {}
title: cmp.is
